### ISSUE TITLE
As a user I would like voice recognition support

### ISSUE THREAD

**Issue by almiche** [jusleg/simple-calculator#44]
**Story Points: 8**

Risk: HIGH

Priority: LOW

## Description
The app should have a mode whereby commands and inputs can made using voice recognition, to allow for hands free calculations that also support usage for the visually impaired.

## Mockup

![Mockup image]()
*Image describing the PR*

## Acceptance Test

| Test Reference | Test Date | Tester | Test Steps | Expected Result | Actual Result |
|----------------|-----------|--------|------------|-----------------|---------------|
| 1              |           |        |            |                 |               |
| 2              |           |        |            |                 |               |
| 3              |           |        |            |                 |               |
| 4              |           |        |            |                 |               |
| 5              |           |        |            |                 |               |

# Tasks

- [ ] **Task Name** - *x* Ideal hour(s) *TASK #*
- [ ] **Task Name** - *x* Ideal hour(s) *TASK #*
- [ ] **Task Name** - *x* Ideal Hour(s) *TASK #*

**Comment by jusleg** [comment]
On second thought, we decided to go against it
